"""Initial migration

Revision ID: 464605ca09ae
Revises: 
Create Date: 2024-05-20 15:09:40.413470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464605ca09ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Actors')
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('Actors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Actors_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Actors_pkey')
    )
    # ### end Alembic commands ###
